version: 2

sphinx:
  configuration: docs/conf.py

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  commands:
    - curl -L https://github.com/git-lfs/git-lfs/releases/download/v3.7.1/git-lfs-linux-amd64-v3.7.1.tar.gz | tar xz && export PATH=$PWD/git-lfs:$PATH && git lfs pull

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
        - test

formats: []
